E-Sports/Models/Trophys.cs
using Microsoft.VisualBasic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace E_Sports.Models
{
    public class Trophys
    {
        public Guid Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public DateTime StartDate { get; set; }
        [Required]
      
        public DateTime EndDate { get; set; }
    }
}

E-Sports/Controllers/TrophyController.cs
using E_Sports.Data;
using E_Sports.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;

namespace E_Sports.Controllers
{
    public class TrophyController : Controller
    {
        private readonly ApplicationDBContext _db;
        public TrophyController(ApplicationDBContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
           IEnumerable<Trophys> objTrophyList = _db.Trophies;
            return View(objTrophyList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Trophys obj)
        {
            if (ModelState.IsValid)
            {
                _db.Trophies.Add(obj);
                _db.SaveChanges();
                TempData["Success"] = "New Trophy created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var TrophiesFromDb = _db.Trophies.Find(id);

            if (TrophiesFromDb == null)
            {
                return NotFound();
            }
            return View(TrophiesFromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Trophys obj)
        {
            if (ModelState.IsValid)
            {
                _db.Trophies.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Trophies updated successfully";

                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var TrophiesFromDb = _db.Trophies.Find(id);
            if (TrophiesFromDb == null)
            {
                return NotFound();
            }
            return View(TrophiesFromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Trophies.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Trophies.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Trophies Deleted successfully";
            return RedirectToAction("Index");

        }

    }
}

E-Sports/Views/Trophy/Create.cshtml
@model Trophys

<form method="post">
    <div class="border p-3 mt-4">
        <h2 class="text-primary"> Add Trophy</h2>
        <hr />
    </div>
    <div class="mb-3">
        <label asp-for="Name">Trophy Name</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Description"> Description</label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="StartDate">Start Date</label>
        <input asp-for="StartDate" class="form-control" />
        <span asp-validation-for="StartDate" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="EndDate">End Date</label>
        <input asp-for="EndDate" class="form-control" />
        <span asp-validation-for="EndDate" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-success" style="width:150px">Create</button>
    <a asp-controller="Trophy" asp-action="Index" class="btn btn-secondary" style="width:150px">
        Go Back
    </a>

</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

E-Sports/Views/Trophy/Delete.cshtml
@model Trophys
<form method="post" asp-action="DeletePOST">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <h2 class="text-primary"> Delete Trophy </h2>
        <hr />
    </div>
    <div class="mb-3">
        <label asp-for="Name">Trophy Name</label>
        <input asp-for="Name" disabled class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" disabled class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="StartDate">Start Date</label>
        <input asp-for="StartDate" disabled class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="EndDate">End Date</label>
        <input asp-for="EndDate" disabled class="form-control" />
    </div>
    <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
    <a asp-controller="Trophy" asp-action="Index" class="btn btn-secondary" style="width:150px">
        Go Back
    </a>

</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

E-Sports/Views/Trophy/Edit.cshtml
@model Trophys

<form method="post">
    <div class="border p-3 mt-4">
        <h2 class="text-primary"> Edit Trophy</h2>
        <hr />
    </div>
    <div class="mb-3">
        <label asp-for="Name">Trophy Name</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Description"> Description</label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="StartDate">Start Date</label>
        <input asp-for="StartDate" class="form-control" />
        <span asp-validation-for="StartDate" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="EndDate">End Date</label>
        <input asp-for="EndDate" class="form-control" />
        <span asp-validation-for="EndDate" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-success" style="width:150px">Update</button>
    <a asp-controller="Trophy" asp-action="Index" class="btn btn-secondary" style="width:150px">
        Go Back
    </a>

</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

E-Sports/Views/Trophy/Index.cshtml
@model IEnumerable<Trophys>
@{
    ViewData["Title"] = "Index";
}

<div class=container p-3">
    <div class="row-pt-4">
        <div class="col-6">
            <h2 class="text-primary">Trophies List</h2>
        </div>
        <div class="col-12 text-end">
            <a asp-action="Create" asp-controller="Trophy" class="btn btn-success">
                <i class="bi bi-plus-square">
                </i> &nbsp; Add New Trophy
            </a>
        </div>
    </div>
</div>
<br />
<br />
<table class="table table-hover">
    <thead>

        <tr class="table-primary">
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
          
            <th scope="col">Actions</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
  
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Trophy" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info mx-2">
                            <i class="bi bi-pencil-square"> </i>Edit
                        </a>
                        <a asp-controller="Trophy" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger mx-2">
                            <i class="bi bi-trash-fill"> </i>Delete
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>